language: node_js
addons:
  chrome: stable
node_js:
  - "10"
  - "12"
  - "14"
  - "16"
env:
  - WEBPACK_VERSION=5
  - WEBPACK_VERSION=4
  - WEBPACK_VERSION=3
install: yarn install --ignore-engines
script: yarn lint && yarn add --dev webpack@$WEBPACK_VERSION --ignore-engines && yarn test
